package org.example.ticketservice.service;

import org.example.ticketservice.dto.TicketCreateDTO;
import org.example.ticketservice.dto.TicketDTO;
import org.example.ticketservice.dto.TicketWithEventDetailsDTO;

import java.util.List;
import java.util.Map;

/**
 * Service interface for managing tickets in the festival management system.
 * Provides operations for CRUD operations, ticket purchasing, revenue calculation, and event validation.
 *
 * @author EscobarTeam
 */
public interface ITicketService {
    /**
     * Retrieves all tickets from the database.
     *
     * @return a list of all {@code TicketDTO} objects representing all tickets
     */
    List<TicketDTO> getAllTickets();
    
    /**
     * Retrieves a ticket by its unique identifier.
     *
     * @param id the unique identifier of the ticket to retrieve
     * @return the {@code TicketDTO} object representing the ticket with the specified ID
     * @throws org.example.ticketservice.exception.TicketNotFoundException if no ticket exists with the given ID
     */
    TicketDTO getTicketById(Long id);
    
    /**
     * Creates a new ticket in the system.
     *
     * @param ticketCreateDTO the DTO containing the data for the new ticket
     * @return the {@code TicketDTO} object representing the newly created ticket
     */
    TicketDTO createTicket(TicketCreateDTO ticketCreateDTO);
    
    /**
     * Updates an existing ticket with new information.
     *
     * @param id the unique identifier of the ticket to update
     * @param ticketDTO the DTO containing the updated ticket information
     * @return the {@code TicketDTO} object representing the updated ticket
     * @throws org.example.ticketservice.exception.TicketNotFoundException if no ticket exists with the given ID
     */
    TicketDTO updateTicket(Long id, TicketDTO ticketDTO);
    
    /**
     * Deletes a ticket from the system by its unique identifier.
     *
     * @param id the unique identifier of the ticket to delete
     * @throws org.example.ticketservice.exception.TicketNotFoundException if no ticket exists with the given ID
     */
    void deleteTicket(Long id);
    
    /**
     * Retrieves all tickets for a specific event.
     *
     * @param eventName the name of the event to filter tickets by
     * @return a list of {@code TicketDTO} objects representing tickets for the specified event
     */
    List<TicketDTO> getTicketsByFestival(String eventName);
    
    /**
     * Calculates the number of available seats for a specific event.
     * This is calculated based on the event capacity minus sold tickets.
     *
     * @param eventName the name of the event
     * @return the number of available seats for the event
     */
    int getAvailableSeats(String eventName);
    
    /**
     * Calculates the total revenue generated by each event.
     *
     * @return a map where keys are event names and values are the total revenue for each event
     */
    Map<String, Double> getRevenueByFestival();
    
    /**
     * Filters tickets by their type (e.g., VIP, GENERAL, EARLY_BIRD).
     *
     * @param ticketType the type of tickets to filter by
     * @return a list of {@code TicketDTO} objects representing tickets of the specified type
     */
    List<TicketDTO> getTicketsByType(String ticketType);
    
    /**
     * Calculates the total revenue from all tickets in the system.
     *
     * @return the total revenue as a {@code Double} value
     */
    Double getTotalRevenue();
    
    /**
     * Retrieves ticket information along with detailed event information.
     * Validates the event exists and provides localized validation messages.
     *
     * @param eventName the name of the event
     * @param language the language code for message localization (e.g., "ro-RO", "en-US")
     * @return a {@code TicketWithEventDetailsDTO} object containing ticket and event details
     * @throws RuntimeException if no tickets exist for the event or if the event is not found
     */
    TicketWithEventDetailsDTO getTicketWithEventDetails(String eventName, String language);
    
    /**
     * Purchases a ticket with validation against the Event Service.
     * Validates that the event exists and adjusts pricing based on region.
     *
     * @param ticketCreateDTO the DTO containing the ticket purchase information
     * @param region the region code for pricing adjustment (e.g., "EU-RO", "US")
     * @param language the language code for message localization (e.g., "ro-RO", "en-US")
     * @return the {@code TicketDTO} object representing the purchased ticket
     * @throws RuntimeException if the event does not exist
     */
    TicketDTO purchaseTicketWithValidation(TicketCreateDTO ticketCreateDTO, String region, String language);
}
